[package]
name = "carbonyl"
version = "0.0.3"
edition = "2021"

[dependencies]
libc = "0.2"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"
chrono = "0.4.23"
dpi = "0.1.2"
rustls = "0.23"
servo = "0.1.0"
url = "2.5.4"
image = "0.24.9"
rascii_art = "0.4.5"

[lib]
name = "carbonyl"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
